### ISSUE TITLE
what's the name of the typeface used?

### ISSUE THREAD

**Issue by bo3OU** [sujan-s/code-blue#1]
What's the name of the typeface/font family used in the ReadMe.md file?

**Comment by BrandonDH** [comment]
Hey @bo3OU I'm not a maintainer of this project but I think I can help. This is the `font-family:` on the `.body-markdown` class from the `readme.md` file: 

`-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol"` Hope this helps!

**Comment by sujan-s** [comment]
@bo3OU Hiya. If you’re referring to the text on the file itself, it depends on the OS you’re using. On MacOS, it’s San Francisco, and on Windows, it’s Segoe UI.

The typeface used in the renders is a custom font made by me, which i’ll publish in a couple of weeks.

**Comment by niccolomineo** [comment]
What's the name of the custom font? Where can it be downloaded?

**Comment by sujan-s** [comment]
The current version is here— https://archetype-foundry.com/

The font you see on the screenshots is a slightly more recent version, which I’m hoping to publish soon.
