### ISSUE TITLE
Improve the changelog file

### ISSUE THREAD

**Issue by mittalyashu** [sujan-s/code-blue#12]
Your current changelog file looks like this:

![image](https://user-images.githubusercontent.com/29014463/44331346-e6d39900-a486-11e8-81fc-400bf4b401eb.png)

---

But if you want you can improve it by using [LogChimp](https://logchimp.now.sh).

This is how it looks if you use LogChimp _([demo](https://mittalyashu.gitlab.io/jasper-changelog/))_.

[![image](https://user-images.githubusercontent.com/29014463/44331425-11255680-a487-11e8-9760-a15969c1e076.png)](https://mittalyashu.gitlab.io/jasper-changelog/)

**Comment by sujan-s** [comment]
Overkill for just a VSCode theme. But LogChimp looks interesting! Maybe I’ll use it elsewhere, for a larger project.
