### ISSUE TITLE
Menu color is brown

### ISSUE THREAD

**Issue by mittalyashu** [sujan-s/code-blue#13]
![code_-_insiders_2018-11-18_14-05-47](https://user-images.githubusercontent.com/29014463/48670828-a5658f00-eb44-11e8-9602-cd3f2c500ef7.png)

**Comment by sujan-s** [comment]
This seems to be a Windows-only thing— I can’t seem to find the option on my Mac. Let me get hold of  a Windows machine, and see if I can tweak it accordingly.

**Comment by DannyShort** [comment]
Quick fix if you still getting this open the settins JSON and paste in the follwoing. 

```JSON
    "workbench.colorCustomizations": {
      "menu.background": "#242B40",
      "dropdown.background":"#242B40",
    },
```
Result

![code blue](https://user-images.githubusercontent.com/3061432/51178456-7eb0a400-18ba-11e9-83f4-254921f0ba76.png)

**Comment by sujan-s** [comment]
Fixed in Danny’s PR.
