### ISSUE TITLE
Microsite install command incorrect

### ISSUE THREAD

**Issue by JamesSkemp** [sujan-s/code-blue#14]
The site at https://sujansundareswaran.com/code-blue/ states that you should run `ext.install Sujan.code-blue` in the command pallette.

Based upon the README and actual command, that should be `ext install Sujan.code-blue`. In addition, the correct spelling is "palette."

> Copy-paste this in your VSCode command pallette—

**Comment by sujan-s** [comment]
Thanks for the heads-up, James. Good catch.

It’s fixed now, but wait for a bit before the S3 cache is invalidated to see the update.
