### ISSUE TITLE
0.9.12 changes intentional?

### ISSUE THREAD

**Issue by e2o** [sujan-s/code-blue#17]
Hello, the new 0.9.12 seems to have some drastic changes and are totally different from the 0.9.11 of this theme. I have a feeling that this was not done intentionally.

This is how the current version looks for me:
![image](https://user-images.githubusercontent.com/6171742/70329514-e4dc4780-183b-11ea-8b89-dc599ea1cbff.png)

VS the "old" version 0.9.11:

![image](https://user-images.githubusercontent.com/6171742/70329591-0f2e0500-183c-11ea-9033-ee6226f58a3c.png)

**Comment by sujan-s** [comment]
Hi Enzo. Thanks for reaching out.
The changes are intentional—I received a significant amount of feedback about the amount of red used in the theme, and hence I toned it down a bit. There are also a few tweaks to some of the other colours, reducing the stark contrast just a wee bit.

**Comment by e2o** [comment]
Okay, thanks for clarifying. I'll pin my version to `0.9.12` then as I prefer that color scheme.
