### ISSUE TITLE
Flutter debugging status bar colour

### ISSUE THREAD

**Issue by ishanray** [sujan-s/code-blue#2]
Great colour scheme! When debugging a flutter app, the status bar looks out of place.

![screen shot 2018-08-05 at 7 21 26 pm](https://user-images.githubusercontent.com/5403397/43691115-feb9d2f8-98e4-11e8-80ef-785f8234fce1.png)

**Comment by sujan-s** [comment]
@ishanray Hiya. This should be fixed now.
