### ISSUE TITLE
Hi ! How to turn menu settings white

### ISSUE THREAD

**Issue by StevenTang1994** [sujan-s/code-blue#22]
How to turn menu settings white，Blue is so dazzling
![image](https://user-images.githubusercontent.com/24404599/100529719-5ec3c880-3225-11eb-9fae-1b7ea2c26865.png)

**Comment by laurocjs** [comment]
You can change it on your settings.json.

Add this:

```
"workbench.colorCustomizations": {
    "menu.foreground": "#fff"
}
```

Refs:
https://code.visualstudio.com/docs/getstarted/themes
https://code.visualstudio.com/api/references/theme-color

**Comment by StevenTang1994** [comment]
> You can change it on your settings.json.
> 
> Add this:
> 
> ```
> "workbench.colorCustomizations": {
>     "menu.foreground": "#fff"
> }
> ```
> 
> Refs:
> https://code.visualstudio.com/docs/getstarted/themes
> https://code.visualstudio.com/api/references/theme-color

thank
