### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by RainedX** [sujan-s/code-blue#4]
I want to know what font in the picture ?

**Comment by sujan-s** [comment]
Hiya! It is a custom font I made myself, and plan to publish it a couple of weeks from now. I’ll let know once its ready.  👍

**Comment by mittalyashu** [comment]
@sujan-s, since so many people are asking the same question about the font, I think you should add in the readme file.

**Comment by sujan-s** [comment]
@mittalyashu Yeah, I should. But the demo font you just downloaded is a fairly dated version, and I plan to released the next version a couple of weeks from now. Once I do that, I’ll update them everywhere. 👍 

Thanks for trying the font, do let me know what you think of that as well :)

**Comment by mittalyashu** [comment]
> But the demo font you just downloaded is a fairly dated version.

Which font? I haven't downloaded any font.

**Comment by sujan-s** [comment]
@s-sujan Dita Grotesk Mono from Archetype Foundry?

**Comment by sujan-s** [comment]
> Which font? I haven't downloaded any font.

@mittalyashu Dita Grotesk Mono?
