### ISSUE TITLE
Field color is brown

### ISSUE THREAD

**Issue by mittalyashu** [sujan-s/code-blue#5]
# Fields color

## Search bar
![image](https://user-images.githubusercontent.com/29014463/43773727-52b15b80-9a64-11e8-9219-d85cef69cc1d.png)

![code_2018-08-07_17-51-22](https://user-images.githubusercontent.com/29014463/43775521-ad1bb7b8-9a6a-11e8-8f7d-78585585859b.png)

## Dropdown list

![image](https://user-images.githubusercontent.com/29014463/43775507-9a4a13f0-9a6a-11e8-9728-b2f4980cc0d5.png)

![2018-08-07_17-53-11](https://user-images.githubusercontent.com/29014463/43775588-db6d7930-9a6a-11e8-8731-605b3cac1b6c.png)

![image](https://user-images.githubusercontent.com/29014463/43775597-e173d5f4-9a6a-11e8-8c2d-29f5bd78e89a.png)

**Comment by sujan-s** [comment]
Dropdown colours are not fixed yet, need to do a few more tests on other OSes. Other input colours are fixed. (I’ll open a separate issue)
