### ISSUE TITLE
Win 10, VScode 1.25.1, not working

### ISSUE THREAD

**Issue by Kaol-Fu** [sujan-s/code-blue#6]
There is nothing change after installing with VScode 1.25.1 Win 10 version.

**Comment by sujan-s** [comment]
@Kaol-Fu You might have to set it separately by going to the Color Theme menu. Open the Command palette with Ctrl+P. Then—

<img width="767" alt="screen shot 2018-08-07 at 7 17 55 pm" src="https://user-images.githubusercontent.com/19920532/43779741-b37a865a-9a76-11e8-9769-c8591bdff3d1.png">

<img width="738" alt="screen shot 2018-08-07 at 7 18 11 pm" src="https://user-images.githubusercontent.com/19920532/43779775-c629a560-9a76-11e8-8a8e-763bf03471c1.png">

**Comment by duranmla** [comment]
I needed this too, thanks very much. It "works now". Hahaha. Nice job mate, thanks for sharing.

**Comment by sujan-s** [comment]
Closing this.
