### ISSUE TITLE
Text in Markdown files rendering as red?

### ISSUE THREAD

**Issue by macintacos** [sujan-s/code-blue#7]
I could've sworn that this theme was rendering regular text as red earlier today in all of my markdown files (aside from obvious color changes like for links/headers/inline-code/etc.). Now almost all of the text is red unless it's some special syntax. Did anything change recently that would explain this behavior? Anything I could change in my settings to get this text back to being white?

![](https://cl.ly/0D0B2e1v3H1S/Image%202018-08-09%20at%201.32.46%20AM.png)

**Comment by sujan-s** [comment]
@macintacos Hiya. Check now? I have no idea how this happened, but should be fixed now. Check any complex JSON file you have too, the braces were also affected.

<img width="494" alt="screen shot 2018-08-09 at 11 40 01 am" src="https://user-images.githubusercontent.com/19920532/43881179-fd72b644-9bc8-11e8-87d2-ee72e7003037.png">

**Comment by macintacos** [comment]
Works! Thanks for the quick turnaround!

**Comment by sujan-s** [comment]
Awesome. Thanks for reporting, helps upping the bar :) 👍
