### ISSUE TITLE
Markdown highlighting; any way to override link formatting when other formatting is used inside the link itself?

### ISSUE THREAD

**Issue by macintacos** [sujan-s/code-blue#8]
Example:
![](https://cl.ly/3t1F0p321x3n/Image%202018-08-10%20at%2011.36.25%20AM.png)

Currently, Code Blue doesn't know how to differentiate formatting when the formatting occurs within a link itself. Would it be possible to get the formatting to supercede the link formatting itself? In the above example, there is italics, raw input, and bold tags, but none of them are caught by the theme.

**Comment by sujan-s** [comment]
This is interesting—
<img width="284" alt="screen shot 2018-08-11 at 8 46 39 am" src="https://user-images.githubusercontent.com/19920532/43987737-12482452-9d43-11e8-8e7f-e5e21505af35.png">

There is theme formatting, but is lost once the parentheses are added. Let me do some more digging and see.

**Comment by sujan-s** [comment]
Closing this until VSCode makes this possible, raised an issue here — https://github.com/Microsoft/vscode/issues/56188
