### ISSUE TITLE
Color for Markdown Inline Raw Text Could be Improved

### ISSUE THREAD

**Issue by macintacos** [sujan-s/code-blue#9]
Naturally this is purely an objective assertion, but I really don't think that the raw text theming within backticks form Markdown files (`like this`) has a nice color the jives well with the rest of the theme. My vote would be to change it to a brighter color; maybe the color that is provided for the parentheses portion of links?

![](https://user-images.githubusercontent.com/19920532/43987737-12482452-9d43-11e8-8e7f-e5e21505af35.png)

I tried manipulating this value in myself  in my user settings but for some reason it wouldn't work; here are the settings I used:

```javascript
"editor.tokenColorCustomizations": {
  "[Code Blue]": {
    "textMateRules": [{
      "scope": "markup.inline.raw",
      "settings": {
        "foreground": "#ff0000",
        "fontStyle": "bold"
      }
    }]
  }
}
```

Totally up to you if you'd change the color, obviously. This is just by far my favorite theme on VSCode so I want to make it perfect if I can 😅

**Comment by sujan-s** [comment]
😁Haha, this is why Code Blue isn’t 1.0 yet— I know there are quite a few areas of improvement. I somewhat agree with you, let me play with a few colours and see what works best. ✌🏻
